version: '3'

tasks:
  run: 
    cmds:
      - go run ./cmd/sso/main.go --config=./config/local.yml
  build:
    cmds:
      - go build ./cmd/sso/main.go
  migrations: 
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations